/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package upx_ecomercee;

import javax.swing.JFrame;

/**
 *
 * @author rafae
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jp_text_imagem = new javax.swing.JPanel();
        Jp_imagem = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_cadastro = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Imagem_principal = new javax.swing.JLabel();
        Jp_secoes = new javax.swing.JPanel();
        Jp_roupas = new javax.swing.JPanel();
        Jp_eletronico = new javax.swing.JPanel();
        Jp_pet = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(0, 0));

        Jp_text_imagem.setBackground(new java.awt.Color(102, 102, 102));
        Jp_text_imagem.setForeground(new java.awt.Color(0, 0, 0));

        Jp_imagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PixelPlace");
        Jp_imagem.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descubra um mundo de");
        Jp_imagem.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("possibilidades de compras");
        Jp_imagem.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("sem sair de casa.");
        Jp_imagem.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        tf_cadastro.setBackground(new java.awt.Color(0, 0, 0));
        tf_cadastro.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        tf_cadastro.setForeground(new java.awt.Color(255, 255, 255));
        tf_cadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_cadastro.setText("Cadastre-se");
        tf_cadastro.setBorder(new javax.swing.border.MatteBorder(null));
        tf_cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tf_cadastro.setOpaque(true);
        tf_cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_cadastroMouseClicked(evt);
            }
        });
        Jp_imagem.add(tf_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 80, -1));

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Login");
        jTextField2.setBorder(new javax.swing.border.MatteBorder(null));
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField2.setOpaque(true);
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        Jp_imagem.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 40, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Gerenciador de Produtos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Jp_imagem.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        Jp_imagem.add(Imagem_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 315));

        javax.swing.GroupLayout Jp_text_imagemLayout = new javax.swing.GroupLayout(Jp_text_imagem);
        Jp_text_imagem.setLayout(Jp_text_imagemLayout);
        Jp_text_imagemLayout.setHorizontalGroup(
            Jp_text_imagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jp_imagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Jp_text_imagemLayout.setVerticalGroup(
            Jp_text_imagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jp_imagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Jp_secoes.setBackground(new java.awt.Color(255, 255, 255));
        Jp_secoes.setForeground(new java.awt.Color(255, 255, 255));

        Jp_roupas.setBackground(new java.awt.Color(102, 102, 102));
        Jp_roupas.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout Jp_roupasLayout = new javax.swing.GroupLayout(Jp_roupas);
        Jp_roupas.setLayout(Jp_roupasLayout);
        Jp_roupasLayout.setHorizontalGroup(
            Jp_roupasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        Jp_roupasLayout.setVerticalGroup(
            Jp_roupasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        Jp_eletronico.setBackground(new java.awt.Color(102, 102, 102));
        Jp_eletronico.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout Jp_eletronicoLayout = new javax.swing.GroupLayout(Jp_eletronico);
        Jp_eletronico.setLayout(Jp_eletronicoLayout);
        Jp_eletronicoLayout.setHorizontalGroup(
            Jp_eletronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        Jp_eletronicoLayout.setVerticalGroup(
            Jp_eletronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Jp_pet.setBackground(new java.awt.Color(102, 102, 102));
        Jp_pet.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout Jp_petLayout = new javax.swing.GroupLayout(Jp_pet);
        Jp_pet.setLayout(Jp_petLayout);
        Jp_petLayout.setHorizontalGroup(
            Jp_petLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );
        Jp_petLayout.setVerticalGroup(
            Jp_petLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Descubra um mundo de possibilidades de compras sem sair de casa!");

        javax.swing.GroupLayout Jp_secoesLayout = new javax.swing.GroupLayout(Jp_secoes);
        Jp_secoes.setLayout(Jp_secoesLayout);
        Jp_secoesLayout.setHorizontalGroup(
            Jp_secoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jp_secoesLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(Jp_secoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jp_secoesLayout.createSequentialGroup()
                        .addComponent(Jp_roupas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(Jp_eletronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(Jp_pet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jp_secoesLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(59, 59, 59)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Jp_secoesLayout.setVerticalGroup(
            Jp_secoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jp_secoesLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(Jp_secoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jp_eletronico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jp_pet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jp_roupas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jp_text_imagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Jp_secoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Jp_text_imagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jp_secoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_cadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_cadastroMouseClicked
        try{
            Cadastro c = new Cadastro();
            c.setVisible(true);
            c.pack();
            c.setLocation(null);
            c.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
            catch(Exception e){
                System.out.println(e);
            }
        dispose();
    }//GEN-LAST:event_tf_cadastroMouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        try{
            Login l = new Login();
            l.setVisible(true);
            l.pack();
            l.setLocation(null);
            l.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
            catch(Exception e){
                System.out.println(e);
        }
        dispose();
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            CadastroProduto cp = new CadastroProduto();
            cp.setVisible(true);
            cp.pack();
            cp.setLocation(null);
            cp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
            catch(Exception e){
                System.out.println(e);
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagem_principal;
    private javax.swing.JPanel Jp_eletronico;
    private javax.swing.JPanel Jp_imagem;
    private javax.swing.JPanel Jp_pet;
    private javax.swing.JPanel Jp_roupas;
    private javax.swing.JPanel Jp_secoes;
    private javax.swing.JPanel Jp_text_imagem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField tf_cadastro;
    // End of variables declaration//GEN-END:variables
}
