DROP DATABASE IF EXISTS ECOMMERCEDB;
CREATE DATABASE ECOMMERCEDB;
USE ECOMMERCEDB;

CREATE TABLE CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    SENHA VARCHAR(30) NOT NULL
);

CREATE TABLE PRODUTOS (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL,
    DESCRICAO VARCHAR(30) NOT NULL,
    PRECO DECIMAL(8, 2) NOT NULL,
    CATEGORIA VARCHAR(30) NOT NULL,
    IMAGEM VARCHAR(150) NOT NULL
);

CREATE TABLE CARRINHO (
    ID_CARRINHO INT AUTO_INCREMENT PRIMARY KEY,
    QUANTIDADE INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE COMPRA (
    ID_TRANSACAO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_TRANSACAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL(8, 2) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

INSERT INTO CLIENTES (NOME, ENDERECO, TELEFONE, EMAIL, SENHA) VALUES
('Hiro', 'Rua, 123', '987654321', 'hiro@gmail.com', '123');

INSERT INTO PRODUTOS (NOME, DESCRICAO, PRECO, CATEGORIA, IMAGEM) VALUES
('Camiseta', 'Camiseta branca de algodão', 29.99, 'Roupas', 'imagem_camiseta.jpg'),
('Celular', 'Smartphone Android', 899.99, 'Eletrônicos', 'imagem_celular.jpg'),
('Livro', 'Livro de ficção', 39.99, 'Livros', 'imagem_livro.jpg');

INSERT INTO CARRINHO (QUANTIDADE, ID_CLIENTE, ID_PRODUTO) VALUES
(2, 1, 1),
(5, 1, 2),
(1, 1, 3);

SELECT CL.NOME, COUNT(*) AS TOTAL_PEDIDOS
FROM CLIENTES CL
INNER JOIN COMPRA C ON CL.ID_CLIENTE = C.ID_CLIENTE
GROUP BY CL.NOME;

SELECT CL.NOME, AVG(C.VALOR_TOTAL) AS MEDIA_COMPRAS
FROM CLIENTES CL
INNER JOIN COMPRA C ON CL.ID_CLIENTE = C.ID_CLIENTE
GROUP BY CL.NOME;

SELECT CATEGORIA, NOME, PRECO
FROM PRODUTOS
ORDER BY CATEGORIA, NOME;


SELECT *
FROM CARRINHO
WHERE ID_CLIENTE = 2;